substitutions:
  name: Outside Environment Sensors

esp8266:
  board: d1_mini

esphome:
  name: outside-environment-sensor
  friendly_name: Outside Environment Sensor

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Outside-Environment-Sensor"
    password: !secret wifi_ap_password

i2c:
  ## I²C Port - For Temp/Pressure sensor
  sda: GPIO5
  scl: GPIO4
  scan: true

sensor:
  ## Temp/Pressure Sensor
  - platform: bmp085
    temperature:
      name: $name Temperature
      id: bme_temp
      filters:
      - calibrate_linear:
         method: exact
         datapoints:
          # Map 0.0 (from sensor) to 1.0 (true value)
          - 6.5 -> 2.5
          - 11.8 -> 5.8
          - 24.5 -> 20.5
    pressure:
      name:  $name Pressure
      id: bme_press
    update_interval: 1s